### ISSUE TITLE
twistd: Unknown command: resolver

### ISSUE THREAD

**Issue by achekalin** [KPACHbIuLLIAnO4/georesolver#4]
**Огромное спасибо за сервер, как раз такой очень нужен!**

Делаю по инструкции:

1. Ставлю новую чистую Ubuntu 16.04. Логинюсь, делаюсь рутом
2. `apt install python python-dev python-virtualenv python-pip`
3. `cd /opt && mkdir geo && cd geo`
4. `virtualenv .`
5. `. ./bin/activate`
6. `pip install twisted pysyge`
7. `git clone https://github.com/KPACHbIuLLIAnO4/georesolver`
8. `cd georesolver`
9. `python setup.py build`
здесь получаю вывод:
```
(geo) root@vm:/opt/geo/georesolver# python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/resolver
copying resolver/resolver.py -> build/lib.linux-x86_64-2.7/resolver
copying resolver/__init__.py -> build/lib.linux-x86_64-2.7/resolver
package init file 'twisted/plugins/__init__.py' not found (or not a regular file)
creating build/lib.linux-x86_64-2.7/twisted
creating build/lib.linux-x86_64-2.7/twisted/plugins
copying twisted/plugins/resolver_plugin.py -> build/lib.linux-x86_64-2.7/twisted/plugins
package init file 'twisted/plugins/__init__.py' not found (or not a regular file)
(geo) root@vm:/opt/geo/georesolver# 
```
Файла twisted/plugins/__init__.py и правда нет. Поискал его на диске, нашел - `/opt/geo/lib/python2.7/site-packages/twisted/plugins/__init__.py`. Переложил файл в `twisted/plugins/`, после этого сборка прошла:
```
root@vm:/opt/geo/georesolver# python setup.py build
running build
running build_py
copying twisted/plugins/__init__.py -> build/lib.linux-x86_64-2.7/twisted/plugins
root@vm:/opt/geo/georesolver# 
```
10. `python setup.py install`

скачал базу, распаковал, теперь запускаю сервер:

11. `twistd resolver --host localhost --port 8080 --file SxGeoCity.dat `

и получаю:

```
Unhandled Error
Traceback (most recent call last):
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/application/app.py", line 669, in run
    config.parseOptions()
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/application/app.py", line 636, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/usage.py", line 262, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/application/app.py", line 653, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
--- <exception caught here> ---
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 217, in getPlugins
    adapted = interface(plugin, None)
  File "/opt/geo/local/lib/python2.7/site-packages/zope/interface/interface.py", line 468, in _call_conform
    return conform(self)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 71, in __conform__
    return self.load()
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 66, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugins/resolver_plugin.py", line 8, in <module>
    from resolver import resolver
  File "/opt/geo/local/lib/python2.7/site-packages/resolver/resolver.py", line 9, in <module>
    from geoservices import factories
exceptions.ImportError: No module named geoservices

Unhandled Error
Traceback (most recent call last):
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/application/app.py", line 671, in run
    print(config)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/usage.py", line 447, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/usage.py", line 484, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/application/app.py", line 653, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
--- <exception caught here> ---
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 217, in getPlugins
    adapted = interface(plugin, None)
  File "/opt/geo/local/lib/python2.7/site-packages/zope/interface/interface.py", line 468, in _call_conform
    return conform(self)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 71, in __conform__
    return self.load()
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugin.py", line 66, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/opt/geo/local/lib/python2.7/site-packages/twisted/plugins/resolver_plugin.py", line 8, in <module>
    from resolver import resolver
  File "/opt/geo/local/lib/python2.7/site-packages/resolver/resolver.py", line 9, in <module>
    from geoservices import factories
exceptions.ImportError: No module named geoservices

Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.  If not specified, the default gid
                       associated with the specified --uid is used.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
                       -o)

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    mail             An email service
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    news             A news server.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    socks            A SOCKSv4 proxy service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server

/opt/geo/bin/twistd: Unknown command: resolver
```

Похоже, что не находит `geoservices`, хотя он присутствует в `/opt/geo/georesolver/resolver/geoservices`.

**Что делать, куда копать?**

Заранее спасибо!

**Comment by KPACHbIuLLIAnO4** [comment]
Добрый день. Я никак не могу это прокомментировать, я этот проект не поддерживаю уже несколько лет. Раньше все работало :)
